In [1]:
import numpy as np

In [2]:
#to do we will work with firbit data.

In [3]:
#Q1 what is the method that we use to find what are the unique element present in the numpy

In [4]:
a= np.array([1,5,3,4,6,9,1,0,2,4,5,8,1,3,4,5,7,9,3])

In [5]:
np.unique(a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.unique(a,return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([1, 3, 1, 3, 3, 3, 1, 1, 1, 2], dtype=int64))

In [7]:
#the above command we can get what are the frequences of all the unique elements.

In [8]:
ele,freq  =np.unique(a,return_counts=True)

In [9]:
ele

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
freq

array([1, 3, 1, 3, 3, 3, 1, 1, 1, 2], dtype=int64)

In [13]:
#last time we worked like a<6 we are always dealing with array and scaler value.
#what if we work with a<b two numpy arrays
#well it will do a element wise comparision.
#but they should be of equal sizes

In [14]:
a = np.array([5,6,8,1,0,6,4])
b = np.array([8,6,4,1,3,1,7])

In [15]:
a<b

array([ True, False, False, False,  True, False,  True])

In [16]:
#just like the mask we have seen till now, but created using two numpy arrays.

In [17]:
a[a<b]

array([5, 0, 4])

In [18]:
b[a<b]

array([8, 3, 7])

In [19]:
len(a[a<b])==len(b[a<b]) #always will be true

True

In [20]:
#we will learn two new methods any and all
#work similar to 'and' and 'or'

In [21]:
np.any(a<b)

True

In [22]:
#np.any() returns true atleast one pair of a and b satisfies the condition.

In [23]:
np.all(a<b)

False

In [24]:
#np.all() retuns ,when every pair if satisfied.

In [25]:
a = np.arange(0,16,2)

In [26]:
a

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [28]:
np.all(a%2==0) #because every element in the array a is even element.

True

In [30]:
np.any(a%2!=0) #since not a single element is odd.

False