In [1]:
#this is a second leacture on numpy

In [1]:
import numpy as np
import pandas as ps

In [2]:
#accessing a element in the numpy array, works sames as list in python both positive and negative.

In [3]:
a = np.array([1,2,3,4,5,6,7,8,9])

In [4]:
a[0]

1

In [5]:
a[1]

2

In [6]:
#negatieve indexes
a[-1]

9

In [7]:
#slicing
a[1:6]

array([2, 3, 4, 5, 6])

In [8]:
a[1:6:3] #a[start:end:step]

array([2, 5])

In [9]:
a[1:8:2]

array([2, 4, 6, 8])

In [10]:
#how can we know what is the dimentions of the array
a.ndim

1

In [11]:
#shape of array?
a.shape

(9,)

In [12]:
#lets tals about operations on numpy

In [13]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [14]:
a+1 #it performs a element wise operation

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [15]:
#but we have worked only on arithmatic operations, what about logocal opearator
a < 6
#it will return a array of boolean values that satifies that logical condition

array([ True,  True,  True,  True,  True, False, False, False, False,
       False, False, False])

In [16]:
#we can use it as a mask.
mask = a<6

In [17]:
a[mask]
#like this

array([1, 2, 3, 4, 5])

In [18]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [19]:
#okay what if i want only even elements fom the array.
mask = a%2==0

In [20]:
mask

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True])

In [21]:
a[mask]

array([ 2,  4,  6,  8, 10, 12])

In [22]:
#now we got the elements that are only even.

In [23]:
#how to find elements that are divisible by two and five
mask = (a%2==0) and (a%5==0)#this you can't do

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [24]:
#so, lets look at that.

In [25]:
mask1 = a%2==0
mask2 = a%5==0

In [26]:
a[mask1 & mask2] #you have to use logical &, as mask1 and mask2 themselfs are numpy arrays.

array([10])

In [27]:
a[(a%2==0) & (a%5==0)]

array([10])

In [28]:
#elements that are devisible by either 2 or 5
a[(a%2==0) | (a%5==0)]

array([ 2,  4,  5,  6,  8, 10, 12])

In [29]:
a = np.array([1,0,1,0,1,0],dtype='bool')
b = np.array([0,0,0,1,1,0],dtype='bool')

In [30]:
a

array([ True, False,  True, False,  True, False])

In [31]:
b

array([False, False, False,  True,  True, False])

In [32]:
a & b

array([False, False, False, False,  True, False])

In [33]:
a | b

array([ True, False,  True,  True,  True, False])

In [46]:
#universal function.

In [47]:
a = np.array([1,2,3,4,5,6])

In [48]:
len(a)

6

In [49]:
#let's do an element wise addition to the array
a + 2

array([3, 4, 5, 6, 7, 8])

In [50]:
#but is there any function that can do did? yes
np.add(a,2)

array([3, 4, 5, 6, 7, 8])

In [51]:
b = np.array([5,8,8,4,6,1])

In [52]:
len(a) == len(b)

True

In [53]:
#remeber np.add() does element wise addition.
np.add(a,b)

array([ 6, 10, 11,  8, 11,  7])

In [54]:
#the above one gives an error, if a and b have different size.

In [55]:
np.mean(a)

3.5

In [56]:
np.mean(b)

5.333333333333333

In [57]:
a

array([1, 2, 3, 4, 5, 6])

In [58]:
np.sum(a)

21

In [59]:
a.sum()

21

In [61]:
#the difference is np.sum() is a universal function and a.sum() is  method that is bounded to the array a
#it is like l.sort() and sorted(l) in python.

In [62]:
#another difference is universal functions does not apply the changes to the data structure.
#but the methods that are bound to the data structures are inplace.

In [63]:
#there is also sort function in numpy arrays
a = np.array([8,6,4,1,2,0,5,4,6,9])

In [65]:
l = np.sort(a)

In [69]:
l  #a is not changed

array([0, 1, 2, 4, 4, 5, 6, 6, 8, 9])

In [70]:
a.sort()

In [71]:
a #a is changed

array([0, 1, 2, 4, 4, 5, 6, 6, 8, 9])

In [72]:
#let's use the airbnb data into the pandas.

In [74]:
#we don't have to use this in feature as we will be working with the pandas import file method. 

In [77]:
path = 'Numpy_2/survey.txt'

In [81]:
data = np.loadtxt(path)

In [82]:
#this is the  airbnd customer data.

In [83]:
#each element represents the survey poll from the customers

In [85]:
#first find the number of people gave the survey.
#use shape
data.shape

(1167,)

In [86]:
total = data.shape[0]

In [89]:
total #total number of elements

1167

In [90]:
#lets find the maximum value of the survey
max_value = np.max(data)

In [91]:
min_value = np.min(data)

In [92]:
max_value,min_value

(10.0, 1.0)

In [93]:
#lets make a mask for detractors <7
detractors_mask = data<7

In [102]:
detractors_data = data[detractors_mask]

In [103]:
#number of detractors
detractors_data

array([5., 4., 4., 5., 1., 5., 5., 1., 4., 5., 4., 4., 4., 5., 1., 4., 1.,
       4., 1., 5., 5., 1., 1., 4., 1., 5., 4., 1., 1., 4., 1., 5., 1., 4.,
       4., 1., 1., 1., 1., 1., 1., 1., 4., 1., 1., 5., 5., 5., 4., 4., 1.,
       4., 1., 4., 1., 5., 1., 1., 5., 4., 4., 4., 4., 1., 4., 5., 4., 4.,
       1., 1., 5., 5., 1., 5., 1., 5., 5., 4., 5., 4., 1., 1., 1., 1., 4.,
       1., 4., 4., 5., 4., 1., 1., 1., 1., 5., 4., 5., 5., 4., 1., 5., 1.,
       4., 4., 1., 1., 1., 4., 4., 5., 5., 4., 5., 5., 5., 1., 4., 1., 5.,
       5., 1., 5., 1., 1., 5., 5., 4., 4., 1., 4., 4., 4., 1., 1., 4., 4.,
       4., 5., 5., 1., 1., 4., 1., 4., 1., 4., 1., 4., 1., 4., 1., 5., 4.,
       4., 5., 1., 4., 5., 5., 5., 1., 5., 4., 1., 1., 5., 5., 5., 4., 5.,
       4., 4., 1., 4., 4., 4., 4., 5., 1., 5., 5., 1., 4., 4., 5., 1., 1.,
       4., 5., 5., 5., 1., 4., 5., 5., 4., 1., 5., 5., 5., 1., 1., 5., 5.,
       1., 1., 1., 4., 5., 5., 4., 4., 4., 5., 1., 4., 1., 4., 5., 4., 5.,
       5., 1., 5., 1., 5.

In [104]:
#similiarly 
pramotors_data = data[data>8]
pramotors_data

array([10.,  9.,  9.,  9.,  9.,  9., 10.,  9.,  9., 10.,  9.,  9.,  9.,
        9.,  9.,  9.,  9., 10., 10.,  9., 10.,  9., 10.,  9.,  9., 10.,
       10.,  9., 10.,  9., 10., 10., 10.,  9.,  9., 10., 10., 10.,  9.,
       10.,  9., 10.,  9.,  9.,  9., 10.,  9.,  9.,  9.,  9.,  9.,  9.,
       10.,  9.,  9.,  9., 10.,  9., 10.,  9.,  9.,  9.,  9.,  9., 10.,
       10.,  9., 10.,  9.,  9., 10.,  9.,  9., 10.,  9.,  9.,  9.,  9.,
        9.,  9.,  9.,  9.,  9.,  9.,  9., 10.,  9.,  9.,  9.,  9.,  9.,
        9.,  9.,  9., 10.,  9.,  9.,  9.,  9.,  9., 10., 10.,  9., 10.,
       10., 10., 10.,  9., 10.,  9.,  9.,  9.,  9.,  9.,  9.,  9., 10.,
        9., 10.,  9., 10.,  9., 10., 10., 10.,  9.,  9., 10., 10.,  9.,
        9.,  9.,  9., 10.,  9.,  9.,  9.,  9., 10., 10.,  9.,  9.,  9.,
       10.,  9.,  9.,  9.,  9.,  9., 10.,  9.,  9.,  9., 10.,  9., 10.,
       10.,  9.,  9.,  9.,  9., 10.,  9., 10.,  9.,  9.,  9.,  9., 10.,
        9., 10.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9

In [105]:
passives_data = data[(data>=7) & (data<=8)]
passives_data

array([7., 7., 7., 7., 8., 8., 8., 7., 7., 7., 8., 8., 7., 8., 8., 8., 8.,
       7., 7., 7., 8., 7., 7., 7., 8., 7., 8., 8., 7., 8., 8., 8., 7., 8.,
       7., 8., 8., 7., 8., 7., 8., 7., 7., 8., 8., 8., 7., 7., 8., 8., 8.,
       7., 7., 7., 8., 7., 7., 8., 7., 7., 7., 8., 7., 7., 8., 8., 8., 7.,
       7., 7., 7., 7., 8., 8., 7., 8., 7., 8., 8., 7., 8., 7., 7., 8., 7.,
       7., 7., 7., 7., 8., 8., 7., 7., 8., 8., 8., 8., 8., 7., 7., 7., 8.,
       7., 8., 8., 7., 7., 8., 8., 7., 7., 8., 7., 7., 8., 8., 8., 7., 7.,
       8., 8., 8., 8., 7., 7., 7., 8., 7., 7., 7., 7., 8., 7., 8., 7., 7.,
       7., 8., 8., 8., 7., 8., 8., 8., 8., 7., 8., 7., 7., 7., 7., 7., 8.,
       7., 7., 7., 7., 8., 7., 8., 8., 7., 7., 8., 8., 7., 8., 8., 7., 7.,
       7., 8., 8., 7., 7., 8., 7., 7., 7., 8., 7., 7., 7., 8., 7., 7., 7.,
       7., 7., 8., 8., 7., 8., 7., 7., 7., 8., 8., 8., 8., 8., 7., 8., 7.,
       7., 8., 7., 7., 8., 7., 8., 8., 7., 7., 8., 8., 8., 7., 8., 8., 7.,
       7., 7., 7., 7., 8.

In [106]:
#lets find the percentages of pramotors
pramotors_perc = (pramotors_data.shape[0]/total)*100

In [107]:
detractors_perc = (detractors_data.shape[0]/total)*100

In [109]:
#net pramotors score
nps = pramotors_perc - detractors_perc

In [110]:
nps

23.73607540702657

In [111]:
#do you think it is a good score, well that depends on the industry to industry.
#incase of internet provider industry even 20 is fine, but do you take it as a good when it is industry of planes. no right