In [9]:
import numpy as np

In [10]:
a = np.arange(1,19).reshape(2,9)

In [11]:
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18]])

In [12]:
a.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [13]:
a.reshape((1,-1))[0]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [14]:
a.size

18

In [15]:
b  = np.where(a%3==0, -2 , a)
b

array([[ 1,  2, -2,  4,  5, -2,  7,  8, -2],
       [10, 11, -2, 13, 14, -2, 16, 17, -2]])

In [16]:
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18]])

In [20]:
a = np.arange(0,5)
b = np.arange(9,15)

In [21]:
a

array([0, 1, 2, 3, 4])

In [22]:
b

array([ 9, 10, 11, 12, 13, 14])

In [23]:
c = np.concatenate((a,b),axis=0)

In [24]:
c

array([ 0,  1,  2,  3,  4,  9, 10, 11, 12, 13, 14])

In [31]:
a

array([0, 1, 2, 3, 4])

In [33]:
b = np.arange(9,14)

In [36]:
np.vstack((a,b))

array([[ 0,  1,  2,  3,  4],
       [ 9, 10, 11, 12, 13]])

In [37]:
np.hstack((a,b))

array([ 0,  1,  2,  3,  4,  9, 10, 11, 12, 13])

In [38]:
#axis in numpy specifies in what direction should the opeartion should be performed on the arrays.

In [39]:
#axis for an array depends on the dimentions of the array.

In [40]:
#for 1 dimentional array you have 1 axis.
#for 2 dimentional array u have two axis, 1st axis represents rows and second axis represents columns.

In [42]:
a = np.arange(0,16).reshape((2,8))
b = np.arange(15,31).reshape((2,8))

In [43]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [44]:
b

array([[15, 16, 17, 18, 19, 20, 21, 22],
       [23, 24, 25, 26, 27, 28, 29, 30]])

In [49]:
np.sum(a,axis = 0) #perform sum in row wise--> 1 row of the a will get in addition with second row of a

array([ 8, 10, 12, 14, 16, 18, 20, 22])

In [48]:
#so above result is sum of the elements along the each columns

In [50]:
np.sum(a,axis=1)

array([28, 92])

In [51]:
np.sum((a,b),axis=0)

array([[15, 17, 19, 21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39, 41, 43, 45]])

In [52]:
#remeber axis = 0 does the opeartions in row wise.
#axis = 1 does the operations in columns wise

In [53]:
numpy_2d_array = np.arange(0,6).reshape((2,3))

In [54]:
#now lets clearly mention the question
#i want sum of all the element in each along their respective rows.
np.sum(numpy_2d_array, axis = 0)

array([3, 5, 7])

In [56]:
#i want the sum of all the elements in each columns along their respective columns.
np.sum(numpy_2d_array,axis = 1)

array([ 3, 12])

In [57]:
#here is the original array
numpy_2d_array

array([[0, 1, 2],
       [3, 4, 5]])

In [58]:
#adding a new row to the numpy_2d_array
b = np.arange(0,numpy_2d_array.shape[1])
b

array([0, 1, 2])

In [70]:
np.concatenate((numpy_2d_array,np.array([b])),axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2]])

In [71]:
np.array([b])

array([[0, 1, 2]])

In [72]:
#in the concatenation opeation all the arrays need to have same dimentions.