In [1]:
#today we are going to work on fiirbt data.

In [2]:
#okay we have seen how to convert a list into numpy array and we have also seen how to create a numpy array with predefined value.
#but what about if we want to create a empty numpy array

In [4]:
import numpy as np

In [7]:
np.empty((8,),dtype = 'U21')

array(['', '', '', '', '', '', '', ''], dtype='<U21')

In [9]:
e = np.empty((10,),dtype='U21')

In [10]:
e.shape

(10,)

In [11]:
e[0]

''

In [17]:
#now lets import the airbnb data
path = 'Numpy_2/survey.txt'

In [18]:
data = np.loadtxt(path)

In [19]:
data.shape

(1167,)

In [28]:
#now create a numpy array empty
result = np.empty(shape = data.shape, dtype = 'U21') #U21 - >unicde with 21bytes

In [29]:
result

array(['', '', '', ..., '', '', ''], dtype='<U21')

In [30]:
data

array([ 7., 10.,  5., ...,  5.,  9., 10.])

In [31]:
#now lets fill all the vvalues less than 7 with word detractors
#above 8 as pramotors
#inbetween passive

In [32]:
mask1 = data<7
mask2= (data>=7) & (data<=8)
mask3 = data>8

In [33]:
result[mask1] = 'Detractors'
result[mask2] = 'Passive'
result[mask3] = 'Pramotors'

In [34]:
result

array(['Passive', 'Pramotors', 'Detractors', ..., 'Detractors',
       'Pramotors', 'Pramotors'], dtype='<U21')

In [36]:
#see how cool is that.
#and the best part is previously we have like 10 different datas, now we have only 3 type of data.

In [37]:
#but is there a way to find out how many unique values we have in the array? yes
np.unique(result)

array(['Detractors', 'Passive', 'Pramotors'], dtype='<U21')

In [38]:
np.unique(data)

array([ 1.,  4.,  5.,  7.,  8.,  9., 10.])

In [39]:
#but there is another cool parameter in this unique method, which gives the frequencies of each type
np.unique(result,return_counts=True)

(array(['Detractors', 'Passive', 'Pramotors'], dtype='<U21'),
 array([332, 226, 609], dtype=int64))

In [45]:
#now lets create the pramotors percentages and detractors percentages
prom_perc = len(result[result=='Pramotors'])/data.shape[0]
detr_perc = len(result[result=='Detractors'])/data.shape[0]

In [46]:
#now lets calcullate the net pramotors score
nps = prom_perc - detr_perc

In [47]:
nps

0.2373607540702657

In [48]:
#let discuss about the 2 dim arrays

In [49]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
#the number of columns in each row should be equal.

In [51]:
arr = np.array([[1,2,3],[4,5,6]])

In [52]:
arr.ndim

2

In [53]:
arr.shape

(2, 3)

In [54]:
arr.size

6

In [55]:
#we will learn about the dimentions much depper when we learn about he concept of axies.

In [56]:
#can we reshape the numpy array? yes we can

In [57]:
arr.reshape((3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [58]:
#first it will convert all the data into 1 dimentional array, regardless of in which dimention it is in.
# then it will convert into the given shape

In [60]:
#let's say you don't know how many columns it takes for a valid rows, then you can just pass number of rows and -1 in number of col.
arr.reshape((3,-1))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [61]:
#it should be valid rows.

In [63]:
arr.reshape((6,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [64]:
arr.reshape((6,-1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [65]:
arr.reshape((1,-1))

array([[1, 2, 3, 4, 5, 6]])

In [66]:
arr.reshape((1,6))

array([[1, 2, 3, 4, 5, 6]])