In [1]:
#today we are going to work on fitbit data.

In [2]:
#okay we have seen how to convert a list into numpy array and we have also seen how to create a numpy array with predefined value.
#but what about if we want to create a empty numpy array

In [2]:
import numpy as np

In [3]:
np.empty((8,),dtype = 'U21')

array(['', '', '', '', '', '', '', ''], dtype='<U21')

In [4]:
e = np.empty((10,),dtype='U21')

In [5]:
e.shape

(10,)

In [6]:
e[0]

''

In [7]:
#now lets import the airbnb data
path = 'Numpy_2/survey.txt'

In [8]:
data = np.loadtxt(path)

In [9]:
data.shape

(1167,)

In [10]:
#now create a numpy array empty
result = np.empty(shape = data.shape, dtype = 'U21') #U21 - >unicde with 21bytes

In [11]:
result

array(['', '', '', ..., '', '', ''], dtype='<U21')

In [12]:
data

array([ 7., 10.,  5., ...,  5.,  9., 10.])

In [14]:
#now lets fill all the values less than 7 with word detractors
#above 8 as pramotors
#inbetween passive

In [15]:
mask1 = data<7
mask2= (data>=7) & (data<=8)
mask3 = data>8

In [16]:
result[mask1] = 'Detractors'
result[mask2] = 'Passive'
result[mask3] = 'Pramotors'

In [17]:
result

array(['Passive', 'Pramotors', 'Detractors', ..., 'Detractors',
       'Pramotors', 'Pramotors'], dtype='<U21')

In [18]:
#see how cool is that.
#and the best part is previously we have like 10 different datas, now we have only 3 type of data.

In [19]:
#but is there a way to find out how many unique values we have in the array? yes
np.unique(result)

array(['Detractors', 'Passive', 'Pramotors'], dtype='<U21')

In [20]:
np.unique(data)

array([ 1.,  4.,  5.,  7.,  8.,  9., 10.])

In [21]:
#but there is another cool parameter in this unique method, which gives the frequencies of each type
np.unique(result,return_counts=True)

(array(['Detractors', 'Passive', 'Pramotors'], dtype='<U21'),
 array([332, 226, 609], dtype=int64))

In [22]:
#now lets create the pramotors percentages and detractors percentages
prom_perc = len(result[result=='Pramotors'])/data.shape[0]
detr_perc = len(result[result=='Detractors'])/data.shape[0]

In [23]:
#now lets calcullate the net pramotors score
nps = prom_perc - detr_perc

In [24]:
nps

0.2373607540702657

In [25]:
#let discuss about the 2 dim arrays

In [26]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
#the number of columns in each row should be equal.

In [28]:
arr = np.array([[1,2,3],[4,5,6]])

In [29]:
arr.ndim

2

In [30]:
arr.shape

(2, 3)

In [31]:
arr.size

6

In [32]:
#we will learn about the dimentions much depper when we learn about he concept of axies.

In [33]:
#can we reshape the numpy array? yes we can

In [34]:
arr.reshape((3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [35]:
#first it will convert all the data into 1 dimentional array, regardless of in which dimention it is in.
# then it will convert into the given shape

In [36]:
#let's say you don't know how many columns it takes for a valid rows, then you can just pass number of rows and -1 in number of col.
arr.reshape((3,-1))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [37]:
#it should be valid rows.

In [38]:
arr.reshape((6,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [39]:
arr.reshape((6,-1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [40]:
arr.reshape((1,-1))

array([[1, 2, 3, 4, 5, 6]])

In [41]:
arr.reshape((1,6))

array([[1, 2, 3, 4, 5, 6]])

In [42]:
a = np.arange(1,13).reshape((4,3))

In [43]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [44]:
#see how easy to create an 2 dimentional array with elements certain range.

In [45]:
#well can we do negative indexing in the reshape for rows? yes we can.
arr.reshape((-1,3))

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
#so the number of rows will automatically selected.

In [47]:
#but you can't give both the values a negative values.
#so it can deal with the one unknown dimention.

In [48]:
#but where do we use this, later on we will be working with matrix, but you have to create a model which accepts the data in 1d
#so you will do arr.reshape((1,-1))

In [49]:
#so models will accepts only in 1dimentional format, but we can make it to accept more than that.

In [50]:
arr = arr.fill((3,2),5)

TypeError: fill() takes exactly 1 argument (2 given)

In [51]:
#can we transform this into some othere shape
arr #2X3

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
arr.T #3X2

array([[1, 4],
       [2, 5],
       [3, 6]])

In [53]:
#but what will happen if we apply transform tha numpy array to 1 dim
b = np.arange(1,9)

In [54]:
b

array([1, 2, 3, 4, 5, 6, 7, 8])

In [55]:
b.T

array([1, 2, 3, 4, 5, 6, 7, 8])

In [56]:
#but look at  this.
c = np.array([list(range(1,12))])

In [57]:
c
#look carefully it is not a 1 dimentional array, it is a 2 dim array 1X12

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [58]:
c.T # now it is 12X1 12 rows with 1column

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [59]:
#how can i convert any ddimentional array to 1 dimentional array
a = np.arange(1,16).reshape((3,5))

In [60]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [61]:
#here is how
a.reshape((1,-1))[0]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [62]:
#now you got the 1 dimentional array

In [63]:
#but is there a short form for this
a.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [64]:
#the method flatten will cconvert any dimentional array to 1 dimentional array

In [65]:
#accessing an element from a two dimentional array.

In [66]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [67]:
#how to use second element in third row
a[2][1]

12

In [68]:
#well it is easy, same like python but it is not a recommanded.
#then what is recommended, and why?

In [69]:
a[2][1] #is a two step process even in numpy.

12

In [71]:
a[2,1] #this is a single step process. and it is a single value --> directly.

12

In [72]:
#but is negative is possible with this notation

In [73]:
#second element from last row
a[-1,1]

12

In [74]:
#see it exits.

In [75]:
!jt -l

Available Themes: 
   chesterish
   grade3
   gruvboxd
   gruvboxl
   monokai
   oceans16
   onedork
   solarizedd
   solarizedl


In [77]:
!jt -t solarizedd

In [78]:
!jt nfs 16

usage: jt [-h] [-l] [-t THEME] [-f MONOFONT] [-fs MONOSIZE] [-nf NBFONT]
          [-nfs NBFONTSIZE] [-tf TCFONT] [-tfs TCFONTSIZE] [-dfs DFFONTSIZE]
          [-ofs OUTFONTSIZE] [-mathfs MATHFONTSIZE] [-m MARGINS]
          [-cursw CURSORWIDTH] [-cursc CURSORCOLOR] [-cellw CELLWIDTH]
          [-lineh LINEHEIGHT] [-altp] [-altmd] [-altout] [-P] [-T] [-N] [-kl]
          [-vim] [-r] [-dfonts]
jt: error: unrecognized arguments: nfs 16


In [79]:
!jt nfs 18

usage: jt [-h] [-l] [-t THEME] [-f MONOFONT] [-fs MONOSIZE] [-nf NBFONT]
          [-nfs NBFONTSIZE] [-tf TCFONT] [-tfs TCFONTSIZE] [-dfs DFFONTSIZE]
          [-ofs OUTFONTSIZE] [-mathfs MATHFONTSIZE] [-m MARGINS]
          [-cursw CURSORWIDTH] [-cursc CURSORCOLOR] [-cellw CELLWIDTH]
          [-lineh LINEHEIGHT] [-altp] [-altmd] [-altout] [-P] [-T] [-N] [-kl]
          [-vim] [-r] [-dfonts]
jt: error: unrecognized arguments: nfs 18


In [84]:
!jt -nfs 20

In [86]:
!jt -t onedork -f roboto -fs 16

In [87]:
#back to numpy
#print all the rows and columsn

In [88]:
a[:,:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [89]:
a[:,1:4]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14]])

In [91]:
a[:,::2] #get all the values from first columns with step size of 2, for all the rows

array([[ 1,  3,  5],
       [ 6,  8, 10],
       [11, 13, 15]])

In [92]:
#but i want all the elements should print in reverse order in theire respective rows
a[:,::-1]

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])

In [93]:
#see how cool is this.

In [94]:
a[::-1,::-1]

array([[15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [95]:
a.T

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [96]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [97]:
a.T[:,::-1]

array([[11,  6,  1],
       [12,  7,  2],
       [13,  8,  3],
       [14,  9,  4],
       [15, 10,  5]])

In [98]:
#see how cool is this operations.

In [99]:
#lets look at the fancy inddexing in the 2D array

In [103]:
#lets get all the vales as true which are less than 7
a<7 #it is going to be a same shape as a

array([[ True,  True,  True,  True,  True],
       [ True, False, False, False, False],
       [False, False, False, False, False]])

In [104]:
a[a<7] #we get in a 1d, a result after we appplied mask will always a 1d, think why? --> hint output is variable

array([1, 2, 3, 4, 5, 6])

In [105]:
#hey we have worked on axis but they are still in confusion. 

In [106]:
#lets use universal funtion to help us the concept.

In [107]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [108]:
np.sum(a) #by default the parameter axis is None

120

In [109]:
#simply it returns sum of all the elements in the 2d array.

In [110]:
#in 2dimentional numpy array we can have only 2 axis
#axis 0
#axis 1

In [111]:
#first remember this
#When you do opearations in vertical directions then use axis = 0
#when you do opeartions or changes in horizontal direction then use axis = 1 

In [112]:
#now lets do
np.sum(a,axis=0)

array([18, 21, 24, 27, 30])

In [113]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [114]:
#1 + 6 + 11 --> 18
#2 + 7 + 12 --> 21
#3 + 8 + 13 --> 24
#4 + 9 + 14 --> 27
#5 + 10 + 15--> 30

In [115]:
np.sum(a,axis=1)

array([15, 40, 65])

In [116]:
a= [[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]]

In [118]:
a = np.array(a)

In [119]:
a.ndim

3

In [123]:
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [120]:
#now we are dealing with  3 dimetional array

In [121]:
np.sum(a)

378

In [127]:
np.sum(a,axis=0) #Vertical

array([[30, 33, 36],
       [39, 42, 45],
       [48, 51, 54]])

In [128]:
np.sum(a,axis=1) #Horizontal

array([[12, 15, 18],
       [39, 42, 45],
       [66, 69, 72]])

In [129]:
np.sum(a,axis=2) #Depth

array([[ 6, 15, 24],
       [33, 42, 51],
       [60, 69, 78]])