In [34]:
import numpy as np

In [7]:
#to do we will work with firbit data.

In [8]:
#Q1 what is the method that we use to find what are the unique element present in the numpy

In [35]:
a= np.array([1,5,3,4,6,9,1,0,2,4,5,8,1,3,4,5,7,9,3])

In [10]:
np.unique(a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.unique(a,return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([1, 3, 1, 3, 3, 3, 1, 1, 1, 2], dtype=int64))

In [12]:
#the above command we can get what are the frequences of all the unique elements.

In [13]:
ele,freq  =np.unique(a,return_counts=True)

In [14]:
ele

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
freq

array([1, 3, 1, 3, 3, 3, 1, 1, 1, 2], dtype=int64)

In [16]:
#last time we worked like a<6 we are always dealing with array and scaler value.
#what if we work with a<b two numpy arrays
#well it will do a element wise comparision.
#but they should be of equal sizes

In [17]:
a = np.array([5,6,8,1,0,6,4])
b = np.array([8,6,4,1,3,1,7])

In [18]:
a<b

array([ True, False, False, False,  True, False,  True])

In [19]:
#just like the mask we have seen till now, but created using two numpy arrays.

In [20]:
a[a<b]

array([5, 0, 4])

In [21]:
b[a<b]

array([8, 3, 7])

In [22]:
len(a[a<b])==len(b[a<b]) #always will be true

True

In [23]:
#we will learn two new methods any and all
#work similar to 'and' and 'or'

In [24]:
np.any(a<b)

True

In [25]:
#np.any() returns true atleast one pair of a and b satisfies the condition.

In [26]:
np.all(a<b)

False

In [27]:
#np.all() retuns ,when every pair if satisfied.

In [28]:
a = np.arange(0,16,2)

In [29]:
a

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [30]:
np.all(a%2==0) #because every element in the array a is even element.

True

In [31]:
np.any(a%2!=0) #since not a single element is odd.

False

In [33]:
!jt -t gruvboxd

In [36]:
#lets work on the fitbit data.

In [37]:
#we have learned about np.any and np.all
#let consider some examples

In [38]:
a = np.array([1,2,3,2])
b = np.array([2,2,3,2])
c = np.array([6,4,4,5])

In [39]:
a<=b

array([ True,  True,  True,  True])

In [40]:
b<=c

array([ True,  True,  True,  True])

In [41]:
mask = (a<=b) & (b<=c)

In [42]:
mask

array([ True,  True,  True,  True])

In [43]:
np.all(mask)

True

In [44]:
np.any(mask)

True

In [45]:
#now lets go to sorting

In [46]:
a = np.array([5,6,2,4,1,0,3,6,4,8,1,0])

In [47]:
np.sort(a)

array([0, 0, 1, 1, 2, 3, 4, 4, 5, 6, 6, 8])

In [48]:
np.argsort(a)

array([ 5, 11,  4, 10,  2,  6,  3,  8,  0,  1,  7,  9], dtype=int64)

In [49]:
np.max(a)

8

In [51]:
np.argmax(a) #index of maximum value --> argmax --> argument of maximum value

9

In [52]:
np.argmin(a)

5

In [54]:
np.argsort(a) #indices of the elements in original array, places in sorted array

array([ 5, 11,  4, 10,  2,  6,  3,  8,  0,  1,  7,  9], dtype=int64)

In [55]:
#so when ever there is arg word in the method, it always returns the indices of the original method with out arg.

In [56]:
#and where can we use

In [57]:
path = 'Numpy_4/fit.txt'

In [71]:
data = np.loadtxt(path,dtype='str')

In [72]:
data[:3]

array([['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
       ['07-10-2017', '6041', 'Sad', '197', '8', 'Inactive'],
       ['08-10-2017', '25', 'Sad', '0', '5', 'Inactive']], dtype='<U10')

In [73]:
data[0][0][:2]

'06'

In [74]:
#first column --> date of that person

In [75]:
#second --> steps
#third --> mood
#fourth --> calories
#fifth --> hours he slept
#sixth --> active/inactive

In [76]:
data.shape

(96, 6)

In [77]:
#96 rows --> 96 records
#6 columns --> 6 features that we discussed above.

In [78]:
#can we work on this data, no as every thing is in string

In [79]:
#first look at the first 5 rows

In [80]:
data[:5]

array([['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
       ['07-10-2017', '6041', 'Sad', '197', '8', 'Inactive'],
       ['08-10-2017', '25', 'Sad', '0', '5', 'Inactive'],
       ['09-10-2017', '5461', 'Sad', '174', '4', 'Inactive'],
       ['10-10-2017', '6915', 'Neutral', '223', '5', 'Active']],
      dtype='<U10')

In [81]:
#lets get the all the dates
dates = data[:,0]

In [84]:
dates

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
       '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
       '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
       '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
       '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
       '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
       '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
       '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
       '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
       '05-12-2017', '06-12-2017', '07-12-2017', '08-12

In [83]:
#calories
calories = data[:,1]

In [86]:
dates,steps,mood,calories,hours_slepts,active = data[:,0], data[:,1], data[:,2], data[:,3], data[:,4], data[:,5]

In [87]:
mood

array(['Neutral', 'Sad', 'Sad', 'Sad', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Sad', 'Sad', 'Sad', 'Happy', 'Sad', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral',
       'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Neutral',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Sad', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Sad', 'Neutral', 'Neutral',
       'Sad', 'Sad', 'Neutral', 'Neutral', 'Happy', 'Neutral', 'Neutral',
       'Sad', 'Neutral', 'Sad', 'Neutral', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Happy', 'Neutral', 'Happy', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Sad', 'Sad', 'Happy', 'Neutral', 'Neutral',
       'Happy'], dtype='<U10')

In [88]:
#can you sort the data using hours slept
data[np.argsort(data[:,-2])]

array([['05-01-2018', '133', 'Sad', '4', '2', 'Inactive'],
       ['08-11-2017', '4068', 'Happy', '131', '2', 'Inactive'],
       ['03-01-2018', '2599', 'Neutral', '84', '2', 'Inactive'],
       ['25-12-2017', '518', 'Sad', '16', '3', 'Inactive'],
       ['10-12-2017', '1648', 'Sad', '53', '3', 'Active'],
       ['15-12-2017', '437', 'Neutral', '14', '3', 'Active'],
       ['09-12-2017', '2909', 'Neutral', '93', '3', 'Active'],
       ['31-12-2017', '36', 'Sad', '1', '3', 'Inactive'],
       ['02-01-2018', '1447', 'Neutral', '47', '3', 'Inactive'],
       ['04-01-2018', '702', 'Sad', '23', '3', 'Inactive'],
       ['07-11-2017', '6041', 'Neutral', '197', '3', 'Inactive'],
       ['01-01-2018', '299', 'Sad', '10', '3', 'Inactive'],
       ['16-12-2017', '1231', 'Neutral', '39', '4', 'Active'],
       ['17-12-2017', '1696', 'Sad', '55', '4', 'Inactive'],
       ['11-12-2017', '799', 'Sad', '25', '4', 'Inactive'],
       ['02-11-2017', '4779', 'Happy', '156', '4', 'Inactive'],
       ['24

In [89]:
#wow great.

In [90]:
#remeber the error that we encountered

In [99]:
dates,steps,mood,calories,hours_slept,active = data.T

In [100]:
mood

array(['Neutral', 'Sad', 'Sad', 'Sad', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Sad', 'Sad', 'Sad', 'Happy', 'Sad', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral',
       'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Neutral',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Sad', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Sad', 'Neutral', 'Neutral',
       'Sad', 'Sad', 'Neutral', 'Neutral', 'Happy', 'Neutral', 'Neutral',
       'Sad', 'Neutral', 'Sad', 'Neutral', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Happy', 'Neutral', 'Happy', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Sad', 'Sad', 'Happy', 'Neutral', 'Neutral',
       'Happy'], dtype='<U10')

In [101]:
#so here is how Transpose is used and solved the unpacking a 2 dimentional array

In [102]:
type(dates)

numpy.ndarray

In [103]:
steps = np.array(steps,dtype='int')

In [104]:
steps

array([5464, 6041,   25, 5461, 6915, 4545, 4340, 1230,   61, 1258, 3148,
       4687, 4732, 3519, 1580, 2822,  181, 3158, 4383, 3881, 4037,  202,
        292,  330, 2209, 4550, 4435, 4779, 1831, 2255,  539, 5464, 6041,
       4068, 4683, 4033, 6314,  614, 3149, 4005, 4880, 4136,  705,  570,
        269, 4275, 5999, 4421, 6930, 5195,  546,  493,  995, 1163, 6676,
       3608,  774, 1421, 4064, 2725, 5934, 1867, 3721, 2374, 2909, 1648,
        799, 7102, 3941, 7422,  437, 1231, 1696, 4921,  221, 6500, 3575,
       4061,  651,  753,  518, 5537, 4108, 5376, 3066,  177,   36,  299,
       1447, 2599,  702,  133,  153,  500, 2127, 2203])

In [105]:
calories = np.array(calories,dtype='int')

In [106]:
hours_slept = np.array(hours_slept, dtype='int')

In [107]:
mask1 = active=='Active'
mask2 = active == 'Inactive'

In [108]:
active[mask1] = '1'
active[mask2] = '0'

In [109]:
active

array(['0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '1',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1',
       '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '1', '1', '1',
       '1', '1', '1', '1', '1', '1', '0', '0', '0', '0', '0', '0', '1',
       '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '0', '1',
       '1', '0', '1', '1', '1', '1', '1', '0', '1', '1', '1', '1', '0',
       '0', '0', '0', '1', '1', '1', '1', '0', '0', '0', '0', '0', '0',
       '0', '0', '1', '0', '1'], dtype='<U10')

In [110]:
active = np.array(active,dtype='int')

In [111]:
np.unique(mood)

array(['Happy', 'Neutral', 'Sad'], dtype='<U10')

In [112]:
np.unique(mood,return_counts=True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'),
 array([40, 27, 29], dtype=int64))

In [113]:
#so mostly he is happy, 40 days out of 96 days.

In [114]:
#what is the average steps that person have taken

In [115]:
np.mean(steps)

2935.9375

In [117]:
np.max(steps)

7422

In [118]:
dates[np.argmax(steps)]

'14-12-2017'

In [119]:
#that is the date that he took maximum steps

In [121]:
calories[np.argmin(steps)] #calories that he burned that he took minimum steps

0

In [122]:
calories[np.argmax(steps)]

243

In [123]:
mood[np.argmax(steps)]

'Happy'

In [124]:
mood[np.argmin(steps)]

'Sad'

In [125]:
active[np.argmax(steps)]

1

In [127]:
active[np.argmin(steps)]

0

In [128]:
mask = mood == 'Sad'

In [129]:
np.mean(steps[mask])

2103.0689655172414

In [137]:
mask1 = mood =='Neutral'
mask2 = mood=='Happy'

In [138]:
np.mean(steps[mask1 | mask2])

3296.4328358208954

In [139]:
np.mean(steps[mask1])

3153.777777777778

In [140]:
np.mean(steps[mask2])

3392.725

In [141]:
#so we can recommand him that he need to walk atleast 3000 steps to be happy or neutral

In [142]:
#lets find out his mood when he is walking more tha 4000 steps

In [143]:
mask = steps>4000

In [144]:
mood[mask]

array(['Neutral', 'Sad', 'Sad', 'Neutral', 'Sad', 'Sad', 'Sad', 'Happy',
       'Neutral', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy',
       'Neutral', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Sad',
       'Happy', 'Happy', 'Neutral', 'Happy', 'Neutral', 'Neutral', 'Sad',
       'Happy', 'Neutral', 'Happy'], dtype='<U10')

In [145]:
np.unique(mood[mask],return_counts=True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'),
 array([22,  9,  7], dtype=int64))

In [146]:
#okay when he walks more than, 4000 steps he is mostly happy

In [147]:
m,c = np.unique(mood[mask],return_counts=True)

In [148]:
(c[0]/np.sum(c))*100

57.89473684210527

In [149]:
#so when he walks more tha 4000,  57% of chance that he is going to be happy

In [150]:
mask = steps<2000

In [151]:
m,c = np.unique(mood[mask],return_counts=True)
(c[0]/np.sum(c))*100

33.33333333333333

In [152]:
mask = hours_slept<5

In [154]:
m,c = np.unique(mood[mask],return_counts=True)
m,c

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'),
 array([ 7,  9, 10], dtype=int64))

In [155]:
#he is more likely going to be sad.

In [156]:
mask = hours_slept>6
m,c = np.unique(mood[mask],return_counts=True)
m,c

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'),
 array([10,  2,  5], dtype=int64))

In [157]:
#if he get more than 6 hours of sleep he is more likely going to be happy

In [158]:
np.mean(hours_slept)

5.21875

In [159]:
#on average he is sleeping 5 hours of sleep.

In [160]:
mask = hours_slept>5
m,c = np.unique(mood[mask],return_counts=True)
m,c

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'),
 array([20,  3, 10], dtype=int64))

In [161]:
#so if he sleep more than his average sleep hours, he is more likely going to be happy. other wise he is going to be sad. 