In [1]:
import numpy as np

In [2]:
import matplotlib.pyplot as plt

In [3]:
#shallow coppy and deep copy

In [6]:
import copy

In [7]:
a=[1,2,3,4]
b = copy.deepcopy(a)

In [8]:
b[2]=18

In [9]:
b

[1, 2, 18, 4]

In [10]:
a

[1, 2, 3, 4]

In [16]:
a= np.arange(4)
b=a.reshape((2,2))

In [17]:
b

array([[0, 1],
       [2, 3]])

In [18]:
a

array([0, 1, 2, 3])

In [19]:
b[0][1]=100

In [20]:
b

array([[  0, 100],
       [  2,   3]])

In [21]:
a

array([  0, 100,   2,   3])