In [1]:
import numpy as np

In [2]:
#today we learn about matrix multiplication 

In [3]:
a = np.arange(1,5).reshape((2,2))
b = np.arange(5,9).reshape((2,2))

In [5]:
a*b #this is a element wise muliplication.

array([[ 5, 12],
       [21, 32]])

In [6]:
a

array([[1, 2],
       [3, 4]])

In [7]:
b

array([[5, 6],
       [7, 8]])

In [8]:
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [9]:
a=5
a1=6

In [10]:
b=np.arange(1,5)
b1 = np.arange(5,9)

In [11]:
c = np.arange(1,13).reshape((3,4))
c1 = np.arange(2,14).reshape((4,3))

In [12]:
e = np.arange(1,13).reshape((2,6))

In [13]:
np.matmul(c,c1)

array([[ 80,  90, 100],
       [184, 210, 236],
       [288, 330, 372]])

In [14]:
np.matmul(c1,c)

array([[ 53,  62,  71,  80],
       [ 98, 116, 134, 152],
       [143, 170, 197, 224],
       [188, 224, 260, 296]])

In [15]:
np.dot(b,b1)

70

In [16]:
np.matmul(b,b1)

70

In [17]:
a = np.arange(0,24).reshape((2,3,4))

In [18]:
b

array([1, 2, 3, 4])

In [19]:
np.dot(a,b)

array([[ 20,  60, 100],
       [140, 180, 220]])

In [20]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])